-- Seed data for the `initiatives` table.
-- Auto-generated by inbox/ingest.py; every statement is idempotent, so
-- re-running the migration on an existing database is a no-op.
INSERT INTO initiatives (title, url, tags)
SELECT 'Stop Otyłości – model pracy z osobami niepełnosprawnymi intelektualnie z otyłością II i III stopnia', NULL, ARRAY['innowacja społeczna','otyłość','niepełnosprawność intelektualna','zdrowie','dieta','aktywność fizyczna','edukacja zdrowotna','praca socjalna','wsparcie środowiskowe','rehabilitacja']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Stop Otyłości – model pracy z osobami niepełnosprawnymi intelektualnie z otyłością II i III stopnia'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['innowacja społeczna','otyłość','niepełnosprawność intelektualna','zdrowie','dieta','aktywność fizyczna','edukacja zdrowotna','praca socjalna','wsparcie środowiskowe','rehabilitacja']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Mobilny Punkt Higieniczny "Szlakiem ludzi bezdomnych"', NULL, ARRAY['bezdomność','higiena','innowacja społeczna','praca socjalna','wsparcie środowiskowe','zdrowie','Stalowa Wola','edukacja zdrowotna']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Mobilny Punkt Higieniczny "Szlakiem ludzi bezdomnych"'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['bezdomność','higiena','innowacja społeczna','praca socjalna','wsparcie środowiskowe','zdrowie','Stalowa Wola','edukacja zdrowotna']::text[]
);

