-- Seed data for the `initiatives` table.
-- Auto-generated by inbox/ingest.py; every statement is idempotent, so
-- re-running the migration on an existing database is a no-op.
INSERT INTO initiatives (title, url, tags)
SELECT 'Stop Otyłości – model pracy z osobami niepełnosprawnymi intelektualnie z otyłością II i III stopnia', NULL, ARRAY['innowacja społeczna','otyłość','niepełnosprawność intelektualna','zdrowie','dieta','aktywność fizyczna','edukacja zdrowotna','praca socjalna','wsparcie środowiskowe','rehabilitacja']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Stop Otyłości – model pracy z osobami niepełnosprawnymi intelektualnie z otyłością II i III stopnia'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['innowacja społeczna','otyłość','niepełnosprawność intelektualna','zdrowie','dieta','aktywność fizyczna','edukacja zdrowotna','praca socjalna','wsparcie środowiskowe','rehabilitacja']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Mobilny Punkt Higieniczny "Szlakiem ludzi bezdomnych"', NULL, ARRAY['bezdomność','higiena','innowacja społeczna','praca socjalna','wsparcie środowiskowe','zdrowie','Stalowa Wola','edukacja zdrowotna']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Mobilny Punkt Higieniczny "Szlakiem ludzi bezdomnych"'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['bezdomność','higiena','innowacja społeczna','praca socjalna','wsparcie środowiskowe','zdrowie','Stalowa Wola','edukacja zdrowotna']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Ankieta „Niepełnosprawność – Szansą na pełnosprawność w pracy i życiu”', NULL, ARRAY['niepełnosprawność','niepełnosprawność intelektualna','praca socjalna','wsparcie środowiskowe','aktywność fizyczna','edukacja zdrowotna','zdrowie','innowacja społeczna']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Ankieta „Niepełnosprawność – Szansą na pełnosprawność w pracy i życiu”'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['niepełnosprawność','niepełnosprawność intelektualna','praca socjalna','wsparcie środowiskowe','aktywność fizyczna','edukacja zdrowotna','zdrowie','innowacja społeczna']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Niepełnosprawność – Szansą na pełnosprawność w pracy i życiu', NULL, ARRAY['niepełnosprawność','niepełnosprawność intelektualna','innowacja społeczna','rehabilitacja','praca socjalna','wsparcie środowiskowe','edukacja zdrowotna','zooterapia','aktywizacja zawodowa']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Niepełnosprawność – Szansą na pełnosprawność w pracy i życiu'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['niepełnosprawność','niepełnosprawność intelektualna','innowacja społeczna','rehabilitacja','praca socjalna','wsparcie środowiskowe','edukacja zdrowotna','zooterapia','aktywizacja zawodowa']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Formularze ZUS: zaświadczenie o stanie zdrowia, wniosek o rentę rodzinną i socjalną', 'https://www.zus.pl', ARRAY['zdrowie','niepełnosprawność','rehabilitacja','praca socjalna','wsparcie środowiskowe','edukacja zdrowotna','innowacja społeczna']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Formularze ZUS: zaświadczenie o stanie zdrowia, wniosek o rentę rodzinną i socjalną'
      AND url IS NOT DISTINCT FROM 'https://www.zus.pl'
      AND tags = ARRAY['zdrowie','niepełnosprawność','rehabilitacja','praca socjalna','wsparcie środowiskowe','edukacja zdrowotna','innowacja społeczna']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Pełna wokanda! – gra edukacyjna o rozprawach sądowych', NULL, ARRAY['niepełnosprawność','niepełnosprawność intelektualna','edukacja zdrowotna','innowacja społeczna','wsparcie środowiskowe','prawo','sąd','gra edukacyjna']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Pełna wokanda! – gra edukacyjna o rozprawach sądowych'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['niepełnosprawność','niepełnosprawność intelektualna','edukacja zdrowotna','innowacja społeczna','wsparcie środowiskowe','prawo','sąd','gra edukacyjna']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Karty lokalizacji sądów – elementy gry do druku', NULL, ARRAY['gra edukacyjna','sąd','prawo','edukacja zdrowotna','innowacja społeczna']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Karty lokalizacji sądów – elementy gry do druku'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['gra edukacyjna','sąd','prawo','edukacja zdrowotna','innowacja społeczna']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Karty pytań o alimenty, sąd, rentę, rozwód i spadek – gra edukacyjna', NULL, ARRAY['prawo','sąd','gra edukacyjna','edukacja zdrowotna','innowacja społeczna','niepełnosprawność','praca socjalna','alimenty','renta','rozwód','spadek']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Karty pytań o alimenty, sąd, rentę, rozwód i spadek – gra edukacyjna'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['prawo','sąd','gra edukacyjna','edukacja zdrowotna','innowacja społeczna','niepełnosprawność','praca socjalna','alimenty','renta','rozwód','spadek']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Karty pytań o alimenty – gra edukacyjna', NULL, ARRAY['alimenty','gra edukacyjna','prawo','sąd','edukacja zdrowotna','innowacja społeczna']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Karty pytań o alimenty – gra edukacyjna'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['alimenty','gra edukacyjna','prawo','sąd','edukacja zdrowotna','innowacja społeczna']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Karty pytań – procedura karna', NULL, ARRAY['prawo','sąd','gra edukacyjna','edukacja zdrowotna','innowacja społeczna']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Karty pytań – procedura karna'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['prawo','sąd','gra edukacyjna','edukacja zdrowotna','innowacja społeczna']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Karty pytań o rentę i sąd – gra edukacyjna', NULL, ARRAY['innowacja społeczna','gra edukacyjna','renta','prawo','sąd','niepełnosprawność','edukacja zdrowotna','aktywizacja zawodowa']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Karty pytań o rentę i sąd – gra edukacyjna'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['innowacja społeczna','gra edukacyjna','renta','prawo','sąd','niepełnosprawność','edukacja zdrowotna','aktywizacja zawodowa']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Karty pytań o rozwód – gra edukacyjna', NULL, ARRAY['edukacja zdrowotna','gra edukacyjna','innowacja społeczna','prawo','rozwód','sąd','alimenty','władza rodzicielska','koszty sądowe','bezpieczeństwo w sądzie']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Karty pytań o rozwód – gra edukacyjna'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['edukacja zdrowotna','gra edukacyjna','innowacja społeczna','prawo','rozwód','sąd','alimenty','władza rodzicielska','koszty sądowe','bezpieczeństwo w sądzie']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Karty pytań o spadku i sądzie', NULL, ARRAY['spadek','prawo','sąd','edukacja zdrowotna','gra edukacyjna','bezpieczeństwo w sądzie','koszty sądowe','innowacja społeczna']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Karty pytań o spadku i sądzie'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['spadek','prawo','sąd','edukacja zdrowotna','gra edukacyjna','bezpieczeństwo w sądzie','koszty sądowe','innowacja społeczna']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Karty zadań: alimenty i wokanda', NULL, ARRAY['alimenty','prawo','sąd','edukacja zdrowotna','gra edukacyjna','innowacja społeczna','bezpieczeństwo w sądzie','koszty sądowe']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Karty zadań: alimenty i wokanda'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['alimenty','prawo','sąd','edukacja zdrowotna','gra edukacyjna','innowacja społeczna','bezpieczeństwo w sądzie','koszty sądowe']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Karty zadań – procedura karna', NULL, ARRAY['prawo','sąd','edukacja zdrowotna','gra edukacyjna','innowacja społeczna','bezpieczeństwo w sądzie','koszty sądowe']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Karty zadań – procedura karna'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['prawo','sąd','edukacja zdrowotna','gra edukacyjna','innowacja społeczna','bezpieczeństwo w sądzie','koszty sądowe']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Pełna Wokanda – karty zadań do gry edukacyjnej', NULL, ARRAY['innowacja społeczna','gra edukacyjna','prawo','sąd','renta','bezpieczeństwo w sądzie','edukacja zdrowotna','niepełnosprawność','praca socjalna']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Pełna Wokanda – karty zadań do gry edukacyjnej'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['innowacja społeczna','gra edukacyjna','prawo','sąd','renta','bezpieczeństwo w sądzie','edukacja zdrowotna','niepełnosprawność','praca socjalna']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Pełna Wokanda – gra edukacyjna o sprawach rozwodowych', NULL, ARRAY['innowacja społeczna','gra edukacyjna','prawo','sąd','rozwód','władza rodzicielska','koszty sądowe','edukacja zdrowotna','bezpieczeństwo w sądzie']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Pełna Wokanda – gra edukacyjna o sprawach rozwodowych'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['innowacja społeczna','gra edukacyjna','prawo','sąd','rozwód','władza rodzicielska','koszty sądowe','edukacja zdrowotna','bezpieczeństwo w sądzie']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Karty zadań: testament i sprawy sądowe', NULL, ARRAY['prawo','spadek','sąd','edukacja zdrowotna','gra edukacyjna','innowacja społeczna','bezpieczeństwo w sądzie','koszty sądowe']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Karty zadań: testament i sprawy sądowe'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['prawo','spadek','sąd','edukacja zdrowotna','gra edukacyjna','innowacja społeczna','bezpieczeństwo w sądzie','koszty sądowe']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Pełna Wokanda – gra edukacyjna o sprawach sądowych', NULL, ARRAY['innowacja społeczna','gra edukacyjna','prawo','sąd','alimenty','rozwód','spadek','renta','władza rodzicielska','edukacja zdrowotna']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Pełna Wokanda – gra edukacyjna o sprawach sądowych'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['innowacja społeczna','gra edukacyjna','prawo','sąd','alimenty','rozwód','spadek','renta','władza rodzicielska','edukacja zdrowotna']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Pełna Wokanda – gra edukacyjna o sądzie', NULL, ARRAY['gra edukacyjna','edukacja zdrowotna','sąd','prawo','bezpieczeństwo w sądzie','innowacja społeczna']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Pełna Wokanda – gra edukacyjna o sądzie'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['gra edukacyjna','edukacja zdrowotna','sąd','prawo','bezpieczeństwo w sądzie','innowacja społeczna']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Gra edukacyjna o prawie: karty pytań o alimenty, sąd, rentę, rozwód i spadek', NULL, ARRAY['innowacja społeczna','gra edukacyjna','prawo','sąd','alimenty','renta','rozwód','spadek','władza rodzicielska','edukacja zdrowotna']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Gra edukacyjna o prawie: karty pytań o alimenty, sąd, rentę, rozwód i spadek'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['innowacja społeczna','gra edukacyjna','prawo','sąd','alimenty','renta','rozwód','spadek','władza rodzicielska','edukacja zdrowotna']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Pełna Wokanda – elementy gry do druku', NULL, ARRAY['gra edukacyjna','edukacja zdrowotna','zdrowie','prawo','sąd','innowacja społeczna']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Pełna Wokanda – elementy gry do druku'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['gra edukacyjna','edukacja zdrowotna','zdrowie','prawo','sąd','innowacja społeczna']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Elementy gry do druku - pudełko', NULL, ARRAY['gra edukacyjna','innowacja społeczna']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Elementy gry do druku - pudełko'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['gra edukacyjna','innowacja społeczna']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Pełna wokanda! – gra edukacyjna', NULL, ARRAY['gra edukacyjna','edukacja zdrowotna','zdrowie','prawo','sąd','innowacja społeczna']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Pełna wokanda! – gra edukacyjna'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['gra edukacyjna','edukacja zdrowotna','zdrowie','prawo','sąd','innowacja społeczna']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Teczka dokumentów – alimenty (elementy gry do druku)', NULL, ARRAY['alimenty','gra edukacyjna','prawo','edukacja zdrowotna','innowacja społeczna']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Teczka dokumentów – alimenty (elementy gry do druku)'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['alimenty','gra edukacyjna','prawo','edukacja zdrowotna','innowacja społeczna']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Teczka dokumentów – elementy gry do druku (prawo karne)', NULL, ARRAY['prawo','prawo karne','gra edukacyjna','edukacja zdrowotna','innowacja społeczna']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Teczka dokumentów – elementy gry do druku (prawo karne)'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['prawo','prawo karne','gra edukacyjna','edukacja zdrowotna','innowacja społeczna']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Teczka dokumentów – elementy gry do druku (renta)', NULL, ARRAY['renta','gra edukacyjna','prawo','edukacja zdrowotna','innowacja społeczna']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Teczka dokumentów – elementy gry do druku (renta)'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['renta','gra edukacyjna','prawo','edukacja zdrowotna','innowacja społeczna']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Teczka dokumentów – elementy gry do druku (rozwód)', NULL, ARRAY['rozwód','prawo','sąd','gra edukacyjna','edukacja zdrowotna','bezpieczeństwo w sądzie','władza rodzicielska','alimenty']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Teczka dokumentów – elementy gry do druku (rozwód)'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['rozwód','prawo','sąd','gra edukacyjna','edukacja zdrowotna','bezpieczeństwo w sądzie','władza rodzicielska','alimenty']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Teczka dokumentów – elementy gry do druku (testament)', NULL, ARRAY['gra edukacyjna','prawo','spadek','edukacja zdrowotna','innowacja społeczna']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Teczka dokumentów – elementy gry do druku (testament)'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['gra edukacyjna','prawo','spadek','edukacja zdrowotna','innowacja społeczna']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Wokanda - elementy gry do druku', NULL, ARRAY['gra edukacyjna','sąd','prawo','edukacja zdrowotna','bezpieczeństwo w sądzie','innowacja społeczna']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Wokanda - elementy gry do druku'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['gra edukacyjna','sąd','prawo','edukacja zdrowotna','bezpieczeństwo w sądzie','innowacja społeczna']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Pełna wokanda – gra planszowa dla osób z niepełnosprawnością intelektualną', NULL, ARRAY['innowacja społeczna','gra edukacyjna','niepełnosprawność','niepełnosprawność intelektualna','prawo','sąd','edukacja zdrowotna','wsparcie środowiskowe','aktywizacja zawodowa']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Pełna wokanda – gra planszowa dla osób z niepełnosprawnością intelektualną'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['innowacja społeczna','gra edukacyjna','niepełnosprawność','niepełnosprawność intelektualna','prawo','sąd','edukacja zdrowotna','wsparcie środowiskowe','aktywizacja zawodowa']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Pełnia zdrowia – pudełko edukacyjne dla osób z niepełnosprawnością intelektualną', NULL, ARRAY['innowacja społeczna','niepełnosprawność','niepełnosprawność intelektualna','zdrowie','edukacja zdrowotna','gra edukacyjna','rehabilitacja','wsparcie środowiskowe','higiena','aktywizacja zawodowa']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Pełnia zdrowia – pudełko edukacyjne dla osób z niepełnosprawnością intelektualną'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['innowacja społeczna','niepełnosprawność','niepełnosprawność intelektualna','zdrowie','edukacja zdrowotna','gra edukacyjna','rehabilitacja','wsparcie środowiskowe','higiena','aktywizacja zawodowa']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Urzędowy ambaras – gra planszowa dla osób z niepełnosprawnością intelektualną', NULL, ARRAY['innowacja społeczna','niepełnosprawność','niepełnosprawność intelektualna','gra edukacyjna','edukacja zdrowotna','aktywizacja zawodowa','praca socjalna','wsparcie środowiskowe','prawo','rehabilitacja']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Urzędowy ambaras – gra planszowa dla osób z niepełnosprawnością intelektualną'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['innowacja społeczna','niepełnosprawność','niepełnosprawność intelektualna','gra edukacyjna','edukacja zdrowotna','aktywizacja zawodowa','praca socjalna','wsparcie środowiskowe','prawo','rehabilitacja']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Wzór CV / dokument rekrutacyjny', NULL, ARRAY['innowacja społeczna','aktywizacja zawodowa','praca socjalna']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Wzór CV / dokument rekrutacyjny'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['innowacja społeczna','aktywizacja zawodowa','praca socjalna']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Paczka pocztowa', NULL, ARRAY['innowacja społeczna','praca socjalna','wsparcie środowiskowe','bezdomność','pomoc rzeczowa']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Paczka pocztowa'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['innowacja społeczna','praca socjalna','wsparcie środowiskowe','bezdomność','pomoc rzeczowa']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Potwierdzenie odbioru dowodu osobistego', NULL, ARRAY['prawo','sąd','bezpieczeństwo w sądzie','koszty sądowe']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Potwierdzenie odbioru dowodu osobistego'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['prawo','sąd','bezpieczeństwo w sądzie','koszty sądowe']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Wniosek o wydanie zaświadczenia o zgłoszeniu utraty lub uszkodzenia dowodu osobistego', NULL, ARRAY['prawo','sąd','bezpieczeństwo w sądzie','innowacja społeczna']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Wniosek o wydanie zaświadczenia o zgłoszeniu utraty lub uszkodzenia dowodu osobistego'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['prawo','sąd','bezpieczeństwo w sądzie','innowacja społeczna']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Karta rejestracyjna bezrobotnego', NULL, ARRAY['aktywizacja zawodowa','praca socjalna','bezrobocie','urząd pracy','szkolenia zawodowe','pomoc społeczna']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Karta rejestracyjna bezrobotnego'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['aktywizacja zawodowa','praca socjalna','bezrobocie','urząd pracy','szkolenia zawodowe','pomoc społeczna']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Oświadczenie o podleganiu ubezpieczeniu zdrowotnemu osoby bezrobotnej', NULL, ARRAY['bezrobocie','urząd pracy','zdrowie','ubezpieczenie zdrowotne','pomoc społeczna','niepełnosprawność','prawo']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Oświadczenie o podleganiu ubezpieczeniu zdrowotnemu osoby bezrobotnej'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['bezrobocie','urząd pracy','zdrowie','ubezpieczenie zdrowotne','pomoc społeczna','niepełnosprawność','prawo']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Polecenie przelewu / Wpłata gotówkowa', NULL, ARRAY['prawo','innowacja społeczna','pomoc społeczna']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Polecenie przelewu / Wpłata gotówkowa'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['prawo','innowacja społeczna','pomoc społeczna']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Potwierdzenie nadania przesyłki poleconej', NULL, ARRAY['pomoc społeczna','pomoc rzeczowa','prawo']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Potwierdzenie nadania przesyłki poleconej'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['pomoc społeczna','pomoc rzeczowa','prawo']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Formularz przekazu pocztowego', NULL, ARRAY['pomoc rzeczowa','pomoc społeczna','prawo','sąd','koszty sądowe']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Formularz przekazu pocztowego'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['pomoc rzeczowa','pomoc społeczna','prawo','sąd','koszty sądowe']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Wniosek o dofinansowanie ze środków PFRON do uczestnictwa w turnusie rehabilitacyjnym', NULL, ARRAY['niepełnosprawność','rehabilitacja','pomoc społeczna','renta','ubezpieczenie zdrowotne','bezdomność','zdrowie']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Wniosek o dofinansowanie ze środków PFRON do uczestnictwa w turnusie rehabilitacyjnym'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['niepełnosprawność','rehabilitacja','pomoc społeczna','renta','ubezpieczenie zdrowotne','bezdomność','zdrowie']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Wniosek o dofinansowanie likwidacji barier w komunikowaniu się', NULL, ARRAY['niepełnosprawność','rehabilitacja','pomoc społeczna','wsparcie środowiskowe','innowacja społeczna','prawo']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Wniosek o dofinansowanie likwidacji barier w komunikowaniu się'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['niepełnosprawność','rehabilitacja','pomoc społeczna','wsparcie środowiskowe','innowacja społeczna','prawo']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Wniosek o dofinansowanie ze środków PFRON na zaopatrzenie w sprzęt rehabilitacyjny', NULL, ARRAY['niepełnosprawność','rehabilitacja','pomoc społeczna','wsparcie środowiskowe','renta','bezrobocie','aktywizacja zawodowa','prawo']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Wniosek o dofinansowanie ze środków PFRON na zaopatrzenie w sprzęt rehabilitacyjny'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['niepełnosprawność','rehabilitacja','pomoc społeczna','wsparcie środowiskowe','renta','bezrobocie','aktywizacja zawodowa','prawo']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Wniosek o sfinansowanie szkolenia w trybie indywidualnym', NULL, ARRAY['szkolenia zawodowe','urząd pracy','aktywizacja zawodowa','bezrobocie','prawo']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Wniosek o sfinansowanie szkolenia w trybie indywidualnym'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['szkolenia zawodowe','urząd pracy','aktywizacja zawodowa','bezrobocie','prawo']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Wniosek o przyznanie bonu stażowego dla osoby bezrobotnej do 30 roku życia', NULL, ARRAY['aktywizacja zawodowa','bezrobocie','urząd pracy','szkolenia zawodowe','prawo','pomoc społeczna']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Wniosek o przyznanie bonu stażowego dla osoby bezrobotnej do 30 roku życia'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['aktywizacja zawodowa','bezrobocie','urząd pracy','szkolenia zawodowe','prawo','pomoc społeczna']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Wniosek o wydanie orzeczenia o stopniu niepełnosprawności', NULL, ARRAY['niepełnosprawność','pomoc społeczna','zdrowie','rehabilitacja','renta','ubezpieczenie zdrowotne','aktywizacja zawodowa','szkolenia zawodowe','prawo']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Wniosek o wydanie orzeczenia o stopniu niepełnosprawności'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['niepełnosprawność','pomoc społeczna','zdrowie','rehabilitacja','renta','ubezpieczenie zdrowotne','aktywizacja zawodowa','szkolenia zawodowe','prawo']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Wniosek o wydanie zaświadczenia o stanie cywilnym', NULL, ARRAY['prawo','sąd','rozwód','spadek','pomoc społeczna','bezpieczeństwo w sądzie','koszty sądowe']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Wniosek o wydanie zaświadczenia o stanie cywilnym'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['prawo','sąd','rozwód','spadek','pomoc społeczna','bezpieczeństwo w sądzie','koszty sądowe']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Wniosek o zmianę nazwiska lub imienia', NULL, ARRAY['prawo','sąd','zmiana nazwiska','zmiana imienia','stan cywilny','urząd stanu cywilnego','dane osobowe']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Wniosek o zmianę nazwiska lub imienia'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['prawo','sąd','zmiana nazwiska','zmiana imienia','stan cywilny','urząd stanu cywilnego','dane osobowe']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Wniosek o wydanie legitymacji dokumentującej niepełnosprawność lub stopień niepełnosprawności', NULL, ARRAY['niepełnosprawność','prawo','pomoc społeczna','orzeczenie o niepełnosprawności','legitymacja osoby niepełnosprawnej','dane osobowe','zmiana nazwiska']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Wniosek o wydanie legitymacji dokumentującej niepełnosprawność lub stopień niepełnosprawności'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['niepełnosprawność','prawo','pomoc społeczna','orzeczenie o niepełnosprawności','legitymacja osoby niepełnosprawnej','dane osobowe','zmiana nazwiska']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Ambaras! Gra edukacyjna o załatwianiu spraw w urzędach', NULL, ARRAY['gra edukacyjna','niepełnosprawność','niepełnosprawność intelektualna','innowacja społeczna','urząd pracy','pomoc społeczna','edukacja zdrowotna','orzeczenie o niepełnosprawności','dane osobowe']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Ambaras! Gra edukacyjna o załatwianiu spraw w urzędach'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['gra edukacyjna','niepełnosprawność','niepełnosprawność intelektualna','innowacja społeczna','urząd pracy','pomoc społeczna','edukacja zdrowotna','orzeczenie o niepełnosprawności','dane osobowe']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Ambaras! - gra edukacyjna o załatwianiu spraw w urzędach', NULL, ARRAY['gra edukacyjna','innowacja społeczna','urząd pracy','pomoc społeczna','aktywizacja zawodowa','bezrobocie','szkolenia zawodowe','dane osobowe','niepełnosprawność','orzeczenie o niepełnosprawności']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Ambaras! - gra edukacyjna o załatwianiu spraw w urzędach'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['gra edukacyjna','innowacja społeczna','urząd pracy','pomoc społeczna','aktywizacja zawodowa','bezrobocie','szkolenia zawodowe','dane osobowe','niepełnosprawność','orzeczenie o niepełnosprawności']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Karty pytań: komunikacja w urzędach', NULL, ARRAY['innowacja społeczna','urząd pracy','aktywizacja zawodowa','szkolenia zawodowe','orzeczenie o niepełnosprawności','niepełnosprawność','praca socjalna','edukacja zdrowotna']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Karty pytań: komunikacja w urzędach'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['innowacja społeczna','urząd pracy','aktywizacja zawodowa','szkolenia zawodowe','orzeczenie o niepełnosprawności','niepełnosprawność','praca socjalna','edukacja zdrowotna']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Karty pytań: załatwianie spraw w urzędach', NULL, ARRAY['innowacja społeczna','edukacja zdrowotna','niepełnosprawność','legitymacja osoby niepełnosprawnej','urząd pracy','pomoc społeczna','bezrobocie','aktywizacja zawodowa','zdrowie']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Karty pytań: załatwianie spraw w urzędach'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['innowacja społeczna','edukacja zdrowotna','niepełnosprawność','legitymacja osoby niepełnosprawnej','urząd pracy','pomoc społeczna','bezrobocie','aktywizacja zawodowa','zdrowie']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Karty pytań: rozmowy telefoniczne z urzędami', NULL, ARRAY['innowacja społeczna','edukacja zdrowotna','gra edukacyjna','pomoc społeczna','urząd pracy','dane osobowe','niepełnosprawność','legitymacja osoby niepełnosprawnej','orzeczenie o niepełnosprawności']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Karty pytań: rozmowy telefoniczne z urzędami'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['innowacja społeczna','edukacja zdrowotna','gra edukacyjna','pomoc społeczna','urząd pracy','dane osobowe','niepełnosprawność','legitymacja osoby niepełnosprawnej','orzeczenie o niepełnosprawności']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Karty pytań - weryfikacja podstawowa', NULL, ARRAY['stan cywilny','zmiana nazwiska','edukacja zdrowotna','szkolenia zawodowe','aktywizacja zawodowa','prawo','innowacja społeczna']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Karty pytań - weryfikacja podstawowa'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['stan cywilny','zmiana nazwiska','edukacja zdrowotna','szkolenia zawodowe','aktywizacja zawodowa','prawo','innowacja społeczna']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Karty pytań: komunikacja w urzędach dla osób z niepełnosprawnością intelektualną', NULL, ARRAY['niepełnosprawność','niepełnosprawność intelektualna','urząd pracy','urząd stanu cywilnego','orzeczenie o niepełnosprawności','praca socjalna','innowacja społeczna','szkolenia zawodowe','prawo']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Karty pytań: komunikacja w urzędach dla osób z niepełnosprawnością intelektualną'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['niepełnosprawność','niepełnosprawność intelektualna','urząd pracy','urząd stanu cywilnego','orzeczenie o niepełnosprawności','praca socjalna','innowacja społeczna','szkolenia zawodowe','prawo']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Karty pytań - miejsce zaawansowane', NULL, ARRAY['innowacja społeczna','pomoc społeczna','niepełnosprawność','orzeczenie o niepełnosprawności','rehabilitacja','urząd pracy','urząd stanu cywilnego','bezrobocie','edukacja zdrowotna']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Karty pytań - miejsce zaawansowane'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['innowacja społeczna','pomoc społeczna','niepełnosprawność','orzeczenie o niepełnosprawności','rehabilitacja','urząd pracy','urząd stanu cywilnego','bezrobocie','edukacja zdrowotna']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Karty pytań: Telefon z urzędu – zaawansowane', NULL, ARRAY['innowacja społeczna','edukacja zdrowotna','dane osobowe','urząd pracy','pomoc społeczna','stan cywilny','ubezpieczenie zdrowotne','bezpieczeństwo w sądzie']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Karty pytań: Telefon z urzędu – zaawansowane'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['innowacja społeczna','edukacja zdrowotna','dane osobowe','urząd pracy','pomoc społeczna','stan cywilny','ubezpieczenie zdrowotne','bezpieczeństwo w sądzie']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Karty pytań – weryfikacja zaawansowana', NULL, ARRAY['stan cywilny','urząd stanu cywilnego','dane osobowe','urząd pracy','aktywizacja zawodowa','szkolenia zawodowe','niepełnosprawność','orzeczenie o niepełnosprawności','legitymacja osoby niepełnosprawnej','pomoc społeczna']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Karty pytań – weryfikacja zaawansowana'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['stan cywilny','urząd stanu cywilnego','dane osobowe','urząd pracy','aktywizacja zawodowa','szkolenia zawodowe','niepełnosprawność','orzeczenie o niepełnosprawności','legitymacja osoby niepełnosprawnej','pomoc społeczna']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Gra edukacyjna o orzeczeniu o niepełnosprawności', NULL, ARRAY['niepełnosprawność','orzeczenie o niepełnosprawności','gra edukacyjna','edukacja zdrowotna','innowacja społeczna','pomoc społeczna','prawo']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Gra edukacyjna o orzeczeniu o niepełnosprawności'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['niepełnosprawność','orzeczenie o niepełnosprawności','gra edukacyjna','edukacja zdrowotna','innowacja społeczna','pomoc społeczna','prawo']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Karty pytań - poczta - podstawowe', NULL, ARRAY['innowacja społeczna','edukacja zdrowotna','szkolenia zawodowe','praca socjalna','pomoc społeczna','urząd pracy','urząd stanu cywilnego','sąd','prawo']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Karty pytań - poczta - podstawowe'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['innowacja społeczna','edukacja zdrowotna','szkolenia zawodowe','praca socjalna','pomoc społeczna','urząd pracy','urząd stanu cywilnego','sąd','prawo']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Urzędowy ambaras – karty pytań o urząd miasta', NULL, ARRAY['innowacja społeczna','gra edukacyjna','urząd stanu cywilnego','prawo','edukacja zdrowotna','pomoc społeczna']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Urzędowy ambaras – karty pytań o urząd miasta'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['innowacja społeczna','gra edukacyjna','urząd stanu cywilnego','prawo','edukacja zdrowotna','pomoc społeczna']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Karty pytań - Urząd Pracy', NULL, ARRAY['aktywizacja zawodowa','bezrobocie','szkolenia zawodowe','urząd pracy','innowacja społeczna','gra edukacyjna']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Karty pytań - Urząd Pracy'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['aktywizacja zawodowa','bezrobocie','szkolenia zawodowe','urząd pracy','innowacja społeczna','gra edukacyjna']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Gra edukacyjna o ulgach i uprawnieniach dla osób z niepełnosprawnością', NULL, ARRAY['niepełnosprawność','gra edukacyjna','legitymacja osoby niepełnosprawnej','orzeczenie o niepełnosprawności','pomoc rzeczowa','rehabilitacja','innowacja społeczna','edukacja zdrowotna']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Gra edukacyjna o ulgach i uprawnieniach dla osób z niepełnosprawnością'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['niepełnosprawność','gra edukacyjna','legitymacja osoby niepełnosprawnej','orzeczenie o niepełnosprawności','pomoc rzeczowa','rehabilitacja','innowacja społeczna','edukacja zdrowotna']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Karty pytań Poczta – zaawansowane', NULL, ARRAY['innowacja społeczna','edukacja zdrowotna','szkolenia zawodowe','poczta','przesyłki','przelew','dokumenty']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Karty pytań Poczta – zaawansowane'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['innowacja społeczna','edukacja zdrowotna','szkolenia zawodowe','poczta','przesyłki','przelew','dokumenty']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Karty pytań - Urząd Miasta - zaawansowane', NULL, ARRAY['innowacja społeczna','edukacja','dokumenty','stan cywilny','zmiana nazwiska','urząd stanu cywilnego','prawo','podatki']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Karty pytań - Urząd Miasta - zaawansowane'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['innowacja społeczna','edukacja','dokumenty','stan cywilny','zmiana nazwiska','urząd stanu cywilnego','prawo','podatki']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Karty pytań - Urząd Pracy (zaawansowane)', NULL, ARRAY['urząd pracy','szkolenia zawodowe','ubezpieczenie zdrowotne','bezrobocie','aktywizacja zawodowa','edukacja','dokumenty','praca socjalna']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Karty pytań - Urząd Pracy (zaawansowane)'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['urząd pracy','szkolenia zawodowe','ubezpieczenie zdrowotne','bezrobocie','aktywizacja zawodowa','edukacja','dokumenty','praca socjalna']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Naklejki na kostkę 12mm - załączniki do finalnego modelu', NULL, ARRAY['innowacja społeczna','edukacja','gra edukacyjna','dokumenty']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Naklejki na kostkę 12mm - załączniki do finalnego modelu'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['innowacja społeczna','edukacja','gra edukacyjna','dokumenty']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Plansza Urzędowy Ambaras', NULL, ARRAY['innowacja społeczna','edukacja','gra edukacyjna','pomoc społeczna','praca socjalna','bezrobocie','urząd pracy','poczta','dokumenty']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Plansza Urzędowy Ambaras'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['innowacja społeczna','edukacja','gra edukacyjna','pomoc społeczna','praca socjalna','bezrobocie','urząd pracy','poczta','dokumenty']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Urzędowy Ambaras – gra edukacyjna', NULL, ARRAY['gra edukacyjna','edukacja','innowacja społeczna','prawo','dokumenty','urząd stanu cywilnego','sąd','pomoc społeczna']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Urzędowy Ambaras – gra edukacyjna'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['gra edukacyjna','edukacja','innowacja społeczna','prawo','dokumenty','urząd stanu cywilnego','sąd','pomoc społeczna']::text[]
);

INSERT INTO initiatives (title, url, tags)
SELECT 'Załączniki do Finalnego modelu - zetony łatwy/trudny', NULL, ARRAY['edukacja','gra edukacyjna','innowacja społeczna','edukacja zdrowotna']::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM initiatives
    WHERE title = 'Załączniki do Finalnego modelu - zetony łatwy/trudny'
      AND url IS NOT DISTINCT FROM NULL
      AND tags = ARRAY['edukacja','gra edukacyjna','innowacja społeczna','edukacja zdrowotna']::text[]
);

